import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import { PropsWithChildren } from "react";
import { MantineProvider } from "@mantine/core";
import { AppShell } from "@/components/AppShell/AppShell";
import { Footer } from "@/components/Footer/Footer";
import { ModalsProvider } from "@mantine/modals";
import {Notifications} from "@mantine/notifications";
import {HeaderContent} from "@/components/HeaderContent/HeaderContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type LayoutProps = PropsWithChildren;

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <ModalsProvider>
            <AppShell footer={<Footer />} headerContent={<HeaderContent/>}>{children}</AppShell>
            <Notifications/>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
