import {Card, Paper, Title} from "@mantine/core";
import {MonthlyProgress} from "@/components/MonthlyProgress/MonthlyProgress";
import {Metadata} from "next";

export const metadata: Metadata = {
    title: {
        template: "%s - Workout tracker",
        default: "Workout tracker",
    },
    description: "Generated by create next app",
};

export default async function Home() {
    return (
        <div className="flex">
            <Paper withBorder className="p-lg">
                <Title order={2}>Activity</Title>
                <MonthlyProgress/>
            </Paper>
        </div>
    );
}
